#!/data/data/com.termux/files/usr/bin/bash
# Puente Termux -> chroot Kali. Requiere root (Magisk debe autorizar Termux).
KALI="/data/local/nhsystem/kali-arm64"
PATHK="export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PROJ="cd /root/watchdog-git"
su -c "chroot $KALI /bin/bash -c '$PATHK; $PROJ && bash scripts/kali-scripts/ctl.sh'"
